language: php

addons:
    chrome: stable

sudo: false

matrix:
    include:
        -   php: 8.0
            env: 'SCENARIO=symfony5'
        -   php: 7.4
            env: 'SCENARIO=symfony5'
        -   php: 7.4
            env: 'symfony3 DEPENDENCIES=lowest'
        -   php: 7.4
            env: 'symfony3 DEPENDENCIES=highest'
        -   php: 7.3
            env: 'SCENARIO=symfony3'
        -   php: 7.2
            env: 'SCENARIO=symfony3'
        -   php: 7.1
            env: 'SCENARIO=symfony3 DEPENDENCIES=highest'

cache:
    directories:
        - $HOME/.composer/cache/files

install:
    - '.scenarios.lock/install "${SCENARIO}" "${DEPENDENCIES}"'
    - bin/updatePantherChromeDriver.sh
    - # additionally place 'chromedriver' file also in folder 'driver' for symfony/panther >=0.9
    - mkdir drivers
    - cp vendor/symfony/panther/chromedriver-bin/chromedriver_linux64 drivers/chromedriver

script:
    - if [ "${TRAVIS_PHP_VERSION:0:3}" = "8.0" ]; then vendor/bin/phpunit -v; else vendor/bin/phpunit -v --coverage-clover=coverage.clover; fi
    - vendor/bin/behat --config=tests/Behat/behat.yml

after_script:
    - wget https://scrutinizer-ci.com/ocular.phar
    - if [ "${TRAVIS_PHP_VERSION:0:3}" != "8.0" ]; php ocular.phar code-coverage:upload --format=php-clover coverage.clover; fi
    - 'travis_retry php vendor/bin/coveralls -v'
