language: php

addons:
    chrome: stable

sudo: false

matrix:
    include:
        -   php: 7.4
            env: 'symfony3 DEPENDENCIES=lowest'
        -   php: 7.4
            env: 'symfony3 DEPENDENCIES=highest'
        -   php: 7.3
            env: 'SCENARIO=symfony3'
        -   php: 7.2
            env: 'SCENARIO=symfony3'
        -   php: 7.1
            env: 'SCENARIO=symfony3 DEPENDENCIES=highest'

cache:
    directories:
        - $HOME/.composer/cache/files

install:
    - '.scenarios.lock/install "${SCENARIO}" "${DEPENDENCIES}"'
    - bin/updatePantherChromeDriver.sh

script:
    - vendor/bin/phpunit -v --coverage-clover=coverage.clover
    - vendor/bin/behat --config=tests/Behat/behat.yml

after_script:
    - wget https://scrutinizer-ci.com/ocular.phar
    - php ocular.phar code-coverage:upload --format=php-clover coverage.clover
    - 'travis_retry php vendor/bin/coveralls -v'
